import React from 'react';

interface LandingPageProps {
  onNavigate: (path: string) => void;
}

const LandingPage: React.FC<LandingPageProps> = ({ onNavigate }) => {
  return (
    <div className="bg-white selection:bg-blue-100">
      {/* SECTION 1 — HERO */}
      <section className="relative pt-20 pb-32 overflow-hidden bg-gradient-to-b from-white to-blue-50/50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex flex-col lg:flex-row items-center gap-16 lg:gap-24">
            <div className="flex-1 text-center lg:text-left z-10">
              <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-white border border-slate-200 text-[#2563EB] text-[11px] font-bold uppercase tracking-widest mb-8 shadow-sm">
                <span className="relative flex h-2 w-2">
                  <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-blue-400 opacity-75"></span>
                  <span className="relative inline-flex rounded-full h-2 w-2 bg-blue-600"></span>
                </span>
                Trusted by eBay resellers worldwide
              </div>

              <h1 className="text-5xl md:text-7xl font-semibold text-[#0F172A] tracking-tight leading-[1.05] mb-8">
                Turn Your Product Photos Into eBay Listings —{' '}
                <span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-600 to-indigo-600">
                  Instantly
                </span>
              </h1>

              <p className="text-xl text-slate-500 max-w-xl mx-auto lg:mx-0 leading-relaxed mb-10">
                AI built for real-world resellers. Upload your product photos and get SEO-ready titles and clean HTML descriptions — written automatically in seconds.
              </p>

              <div className="flex flex-col sm:flex-row items-center justify-center lg:justify-start gap-4">
                <button
                  onClick={() => onNavigate('/builder')}
                  className="bg-[#2563EB] text-white px-10 py-4 rounded-full text-lg font-bold hover:bg-blue-700 transition-all shadow-xl hover:-translate-y-1"
                >
                  Create My First Listing Free
                </button>
                <button className="bg-white text-slate-600 px-10 py-4 rounded-full text-lg font-semibold border border-slate-200 hover:bg-slate-50">
                  Watch Demo
                </button>
              </div>
            </div>

            {/* Right preview unchanged */}
          </div>
        </div>
      </section>

      {/* SECTION 3 — FULL SAMPLE LISTING */}
      <section className="py-24 px-4 bg-slate-50/40">
        <div className="max-w-5xl mx-auto">
          <div className="text-center mb-12">
            <h2 className="text-xs font-bold text-[#2563EB] uppercase tracking-[0.3em] mb-3">
              Sample Listing Output
            </h2>
            <h3 className="text-3xl font-semibold text-[#0F172A] mb-3">
              Real eBay-style copy — generated from a single photo.
            </h3>
            <p className="text-slate-500 max-w-2xl mx-auto">
              Clean, collector-grade HTML your buyers instantly trust. No fluff. No robotic phrasing.
            </p>
          </div>

          <div className="bg-slate-50 p-6 sm:p-8 rounded-[32px] border border-slate-200 shadow-inner">
            <div className="bg-white rounded-2xl border border-slate-200 shadow-sm p-6 sm:p-10 space-y-8 max-w-3xl mx-auto">

              {/* Title */}
              <div>
                <div className="inline-flex items-center px-3 py-1 rounded-full bg-blue-50 border border-blue-100 text-[10px] font-bold uppercase tracking-[0.2em] text-blue-700 mb-3">
                  Generated by AI
                </div>
                <h4 className="text-2xl font-bold text-[#0F172A] leading-snug">
                  Commodore Plus 4 Canadian NTSC Le Nouveau Boxed Computer System 1984 Complete
                </h4>
              </div>

              <hr className="border-slate-100" />

              {/* System Detected */}
              <div>
                <h5 className="text-xs font-semibold tracking-[0.3em] uppercase text-slate-400 flex items-center gap-2 mb-3">
                  💾 System Detected
                </h5>
                <div className="border border-emerald-200 bg-emerald-50/60 rounded-xl px-4 py-3 text-sm text-slate-800">
                  <strong>&gt; SYSTEM_LOG_1984:</strong> This unit is the rare <strong>Canadian NTSC Commodore Plus/4</strong> with the bilingual
                  <strong> “Le Nouveau”</strong> retail box — a productivity workhorse from the 264 series, frozen in time.
                </div>
              </div>

              <hr className="border-slate-100" />

              {/* Specs + Condition */}
              <div className="grid gap-6 md:grid-cols-2">
                <div className="bg-slate-50 rounded-xl p-5 border border-slate-100">
                  <h5 className="text-xs font-semibold tracking-[0.3em] uppercase text-slate-400 mb-3">
                    🛠 Hardware Specs
                  </h5>
                  <ul className="list-disc pl-5 space-y-1 text-sm text-slate-700">
                    <li><strong>Model:</strong> Canadian NTSC Plus/4</li>
                    <li><strong>CPU:</strong> 7501 / 8501 8-bit</li>
                    <li><strong>ROM:</strong> 3-Plus-1 productivity suite</li>
                    <li><strong>Keyboard:</strong> Full travel, dark case</li>
                    <li><strong>Region:</strong> North American NTSC</li>
                  </ul>
                </div>

                <div className="bg-slate-50 rounded-xl p-5 border border-slate-100">
                  <h5 className="text-xs font-semibold tracking-[0.3em] uppercase text-slate-400 mb-3">
                    👀 Visual & Technical
                  </h5>
                  <p className="text-sm text-slate-700 mb-2">
                    Clean casing, intact legends, original foam inserts. Box shows honest shelf wear and tape from storage.
                  </p>
                  <p className="text-sm text-slate-700">
                    Sold as <strong>unverified / display-ready hardware</strong> — ideal for collectors or restoration specialists.
                  </p>
                </div>
              </div>

              <hr className="border-slate-100" />

              {/* Checklist */}
              <div>
                <h5 className="text-xs font-semibold tracking-[0.3em] uppercase text-slate-400 mb-3">
                  ✅ Peripheral Checklist
                </h5>
                <ul className="space-y-1 text-sm text-slate-700">
                  <li>✅ Console main unit</li>
                  <li>✅ Original power supply</li>
                  <li>✅ “Le Nouveau” retail box</li>
                  <li>✅ Polyfoam inserts</li>
                  <li>✅ Bilingual manuals</li>
                </ul>
              </div>

              <hr className="border-slate-100" />

              {/* Shipping */}
              <div>
                <h5 className="text-xs font-semibold tracking-[0.3em] uppercase text-slate-400 mb-3">
                  📦 Shipping & Handling
                </h5>
                <p className="text-sm text-slate-700">
                  Heavy-duty bubble wrap, double-boxed, shipped from a smoke-free environment with tracking uploaded immediately.
                </p>
                <p className="text-sm text-slate-700 mt-2">
                  ✨ <strong>Ready to list:</strong> paste directly into eBay — no cleanup required.
                </p>
              </div>

            </div>
          </div>
        </div>
      </section>

      <style>{`
        @keyframes scan {
          0%, 100% { top: 0%; }
          50% { top: 100%; }
        }
      `}</style>
    </div>
  );
};

export default LandingPage;
