import React from 'react';

const PrivacyPage: React.FC = () => {
  return (
    <div className="!bg-white dark:!bg-slate-900 min-h-screen pb-32 transition-colors duration-300">
      {/* Header */}
      <section className="pt-24 pb-16 px-4 text-center max-w-4xl mx-auto border-b border-slate-100 dark:border-slate-800">
        <div className="inline-block px-4 py-1.5 bg-slate-50 dark:bg-slate-800 border border-slate-100 dark:border-slate-700 rounded-full text-slate-500 dark:text-slate-400 text-[10px] font-bold uppercase tracking-widest mb-4">
          Last Updated: February 2026
        </div>
        <h1 className="text-4xl md:text-5xl font-semibold text-slate-900 dark:text-white tracking-tight mb-6">
          Privacy Policy
        </h1>
        <p className="text-lg text-slate-500 dark:text-slate-400 leading-relaxed max-w-2xl mx-auto">
          Built by resellers, for resellers. We protect your data as if it were our own.
        </p>
      </section>

      {/* Content */}
      <div className="max-w-3xl mx-auto px-4 mt-20 space-y-16">
        
        <section>
          <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-4 text-left">The Reseller's Promise</h2>
          <p className="text-slate-600 dark:text-slate-300 leading-relaxed">
            Sellistio is designed to solve the "death pile" problem and maximize your eBay Cassini ranking. We understand that your sourcing secrets are your business. Our promise is absolute: <strong>Your data is used to build your listings, not to compete with your business.</strong>
          </p>
        </section>

        <section className="space-y-6">
          <h2 className="text-2xl font-bold text-slate-900 dark:text-white">Information We Secure</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="p-6 bg-slate-50 dark:bg-slate-800 rounded-2xl border border-slate-100 dark:border-slate-700">
              <h4 className="font-bold text-slate-900 dark:text-white mb-2">Account Identity</h4>
              <p className="text-sm text-slate-500 dark:text-slate-400 leading-relaxed">Secure authentication via email so your drafts and inventory stay private to you.</p>
            </div>
            <div className="p-6 bg-slate-50 dark:bg-slate-800 rounded-2xl border border-slate-100 dark:border-slate-700">
              <h4 className="font-bold text-slate-900 dark:text-white mb-2">Listing Intelligence</h4>
              <p className="text-sm text-slate-500 dark:text-slate-400 leading-relaxed">Photos and specs used to generate high-fidelity titles and condition reports.</p>
            </div>
          </div>
        </section>

        {/* Strategic Audit Trust Section */}
        <section className="bg-[#0F172A] dark:bg-black p-10 rounded-[32px] text-white transition-colors">
          <h2 className="text-2xl font-bold mb-6">Reseller Data Protection</h2>
          <div className="space-y-4">
            <div className="flex gap-4">
              <div className="w-6 h-6 rounded-full bg-blue-500/20 text-blue-400 flex items-center justify-center shrink-0">✓</div>
              <p className="text-slate-300"><strong>No Sourcing Data Sales.</strong> We never sell your item locations or sourcing habits to third parties.</p>
            </div>
            <div className="flex gap-4">
              <div className="w-6 h-6 rounded-full bg-blue-500/20 text-blue-400 flex items-center justify-center shrink-0">✓</div>
              <p className="text-slate-300"><strong>Ownership Remains Yours.</strong> You retain 100% ownership of all images and text generated by Sellistio.</p>
            </div>
            <div className="flex gap-4">
              <div className="w-6 h-6 rounded-full bg-blue-500/20 text-blue-400 flex items-center justify-center shrink-0">✓</div>
              <p className="text-slate-300"><strong>AI Transparency.</strong> We utilize the Gemini API for high-fidelity vision processing. Your photos are not used for public model training.</p>
            </div>
          </div>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-4 text-left">Data Rights</h2>
          <p className="text-slate-600 dark:text-slate-300 leading-relaxed mb-4">
            Professional sellers demand control over their digital footprint. You have the right to:
          </p>
          <ul className="space-y-4">
            <li className="flex gap-3 text-slate-600 dark:text-slate-300">
              <span className="text-blue-600 dark:text-blue-400 font-bold">→</span>
              <span><strong>Instant Deletion:</strong> Request full account and data removal at any time.</span>
            </li>
            <li className="flex gap-3 text-slate-600 dark:text-slate-300">
              <span className="text-blue-600 dark:text-blue-400 font-bold">→</span>
              <span><strong>Portability:</strong> Export your generated listings for use on any platform.</span>
            </li>
          </ul>
        </section>

        <section className="border-t border-slate-100 dark:border-slate-800 pt-16 text-center">
          <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-4">Contact Our Privacy Team</h2>
          <p className="text-slate-500 dark:text-slate-400 mb-8">
            Built by Juan Acuna of TreasuTiques. We are here to support your growth.
          </p>
          <a href="mailto:privacy@sellistio.com" className="text-[#2563EB] dark:text-blue-400 font-bold text-lg hover:underline underline-offset-4">
            privacy@sellistio.com
          </a>
        </section>

      </div>
    </div>
  );
};

export default PrivacyPage;
